"""Supervise a local Mosquitto process (native package — not Docker)."""

from __future__ import annotations

import logging
import os
import shutil
import signal
import subprocess
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def write_mosquitto_conf(
    conf_path: Path,
    *,
    data_dir: Path,
    log_dir: Path,
    passwords: Path,
    acl: Path,
    listen_host: str = "0.0.0.0",
    listen_port: int = 1883,
) -> Path:
    """Write a simple password+ACL mosquitto config for the agent-managed broker."""
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(
        f"""# Generated by iot-gateway-agent — do not edit by hand.
listener {listen_port} {listen_host}
allow_anonymous false
password_file {passwords.as_posix()}
acl_file {acl.as_posix()}

persistence true
persistence_location {data_dir.as_posix()}/
log_dest file {log_dir.as_posix()}/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
""",
        encoding="utf-8",
    )
    return conf_path


class MosquittoSupervisor:
    """Start/stop mosquitto as a child of the agent."""

    def __init__(self, conf_path: Path, *, binary: str | None = None):
        self.conf_path = Path(conf_path)
        self.binary = binary or shutil.which("mosquitto") or "mosquitto"
        self._proc: Optional[subprocess.Popen] = None

    @property
    def available(self) -> bool:
        return shutil.which(self.binary) is not None or Path(self.binary).is_file()

    def running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def start(self) -> None:
        if self.running():
            return
        if not self.available:
            raise FileNotFoundError(
                "mosquitto binary not found — provisioner should apt-install mosquitto"
            )
        log = open(  # noqa: SIM115
            self.conf_path.parent / "mosquitto-stdout.log", "a", encoding="utf-8"
        )
        self._proc = subprocess.Popen(
            [self.binary, "-c", str(self.conf_path)],
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        time.sleep(0.3)
        if self._proc.poll() is not None:
            raise RuntimeError(
                f"mosquitto exited immediately (code {self._proc.returncode}); "
                f"see {self.conf_path.parent / 'mosquitto-stdout.log'}"
            )
        logger.info("mosquitto started pid=%s conf=%s", self._proc.pid, self.conf_path)

    def stop(self, *, grace: float = 5.0) -> None:
        if not self.running() or self._proc is None:
            return
        try:
            os.killpg(self._proc.pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError, OSError):
            self._proc.terminate()
        deadline = time.time() + grace
        while time.time() < deadline and self._proc.poll() is None:
            time.sleep(0.1)
        if self._proc.poll() is None:
            try:
                os.killpg(self._proc.pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError, OSError):
                self._proc.kill()
        self._proc = None
