listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl

listener 18883 127.0.0.1
enable_proxy_protocol 1

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_timestamp true

log_type error
log_type warning
log_type notice
log_type information
log_type all

log_timestamp true

persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db

message_size_limit 4096
max_packet_size 8192