services:
  promtail:
    build:
      context: promtail/build
    container_name: promtail
    volumes:
      - ./promtail/config/promtail-config.yaml:/etc/promtail/config.yaml
      - ./mosquitto/log:/mosquitto/log:ro
      - ./nodered/data:/data:ro
      - ./haproxy/logs:/haproxy-logs:ro
      - ./logs:/var/log/iot-gateway:ro
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Ho_Chi_Minh

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot-mosquitto
    network_mode: host
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./certs:/certs:ro
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    environment:
      - TZ=Asia/Ho_Chi_Minh

  haproxy:
    build:
      context: ./haproxy/build
    container_name: iot-haproxy
    network_mode: host
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./certs:/etc/ssl/certs:ro
      - ./haproxy/logs:/var/log/haproxy
    depends_on:
      - mosquitto
    environment:
      - TZ=Asia/Ho_Chi_Minh

  nodered:
    build: 
      context: ./nodered/build
    container_name: iot-nodered
    network_mode: host
    volumes:
      - ./nodered/data:/data
    environment:
      - TZ=Asia/Ho_Chi_Minh  

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
      - ./node-exporter/textfile_collector:/textfile:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|run|var/lib/docker)(/|$$)'
      - '--collector.hwmon'
      - '--collector.textfile.directory=/textfile'
    environment:
      - TZ=Asia/Ho_Chi_Minh

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    restart: unless-stopped

  sync-config:
    build:
      context: ./sync-config/build
    container_name: sync-config
    restart: unless-stopped
    volumes:
      - ./haproxy/allowed-ips.txt:/config/allowed-ips.txt:ro
      - ./mosquitto/config/acl:/config/acl:ro
      - ./node-exporter/textfile_collector:/textfile
      - ./logs:/var/log/iot-gateway
  connected-sensors:
    build:
      context: ./connected-sensors/build
    container_name: iot-connected-sensors
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto/log:/mosquitto/log:ro
      - ./node-exporter/textfile_collector:/textfile
      - ./logs:/var/log/iot-gateway
    environment:
      - TZ=Asia/Ho_Chi_Minh

  ids:
    build:
      context: ./ids
      dockerfile: build/Dockerfile
    container_name: iot-ids
    restart: unless-stopped
    depends_on:
      - nodered
    volumes:
      - ./nodered/data/logs:/app/nodered_logs:ro
      - ./mosquitto/log:/mosquitto/log:ro
      - ./haproxy/logs:/haproxy-logs:ro
      - ./node-exporter/textfile_collector:/textfile:ro
      - ./ids/configs:/app/configs:ro
      - ./logs:/var/log/iot-gateway
    environment:
      - TZ=Asia/Ho_Chi_Minh
