"""Generate app-managed Loki/Prometheus compose variants (Linux vs Windows/WSL2)."""

from __future__ import annotations

import shutil
from enum import Enum
from pathlib import Path

_ASSETS = Path(__file__).resolve().parent / "assets"

LOKI_IMAGE = "grafana/loki:latest"
PROM_IMAGE = "prom/prometheus:latest"
PROJECT_NAME = "iotgw-telemetry"


class ComposeProfile(str, Enum):
    """OS / engine networking profiles for monitoring backends."""

    # Loki publishes 3100; Prometheus uses host network (typical Ubuntu).
    LINUX_HOST = "linux_host"
    # Both on bridge with published ports (Linux alternate / WSL2-friendly).
    LINUX_BRIDGE = "linux_bridge"
    # WSL2 Ubuntu: Loki 0.0.0.0:3100; Prometheus localhost-only 9090.
    WSL2 = "wsl2"
    # Docker Desktop on Windows (no host network): publish both ports.
    WINDOWS_DOCKER_DESKTOP = "windows_docker_desktop"


def _loki_service(*, publish: str = "3100:3100") -> str:
    # Named volume avoids host UID permission issues (Loki runs non-root).
    return f"""  loki:
    image: {LOKI_IMAGE}
    container_name: iotgw-loki
    ports:
      - "{publish}"
    volumes:
      - iotgw_loki_data:/loki
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
"""


def _prometheus_host() -> str:
    return f"""  prometheus:
    image: {PROM_IMAGE}
    container_name: iotgw-prometheus
    network_mode: host
    volumes:
      - iotgw_prom_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.listen-address=0.0.0.0:9090
    restart: unless-stopped
"""


def _prometheus_bridge(*, publish: str = "9090:9090") -> str:
    return f"""  prometheus:
    image: {PROM_IMAGE}
    container_name: iotgw-prometheus
    ports:
      - "{publish}"
    volumes:
      - iotgw_prom_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.listen-address=0.0.0.0:9090
    restart: unless-stopped
"""


_HEADER = """# Generated by apps/control-service/telemetry — do not edit by hand.
# User never runs compose; the control service owns start/stop/status.
services:
"""

_VOLUMES = """
volumes:
  iotgw_loki_data:
  iotgw_prom_data:
"""


def generate_compose_yaml(profile: ComposeProfile | str) -> str:
    """Return docker-compose YAML for the given profile."""
    profile = ComposeProfile(profile)
    if profile is ComposeProfile.LINUX_HOST:
        body = _loki_service(publish="3100:3100") + _prometheus_host()
    elif profile is ComposeProfile.LINUX_BRIDGE:
        body = _loki_service(publish="3100:3100") + _prometheus_bridge(
            publish="9090:9090"
        )
    elif profile is ComposeProfile.WSL2:
        # Loki must listen on 0.0.0.0 inside WSL for portproxy; Prom stays local.
        body = _loki_service(publish="0.0.0.0:3100:3100") + _prometheus_bridge(
            publish="127.0.0.1:9090:9090"
        )
    elif profile is ComposeProfile.WINDOWS_DOCKER_DESKTOP:
        body = _loki_service(publish="3100:3100") + _prometheus_bridge(
            publish="9090:9090"
        )
    else:  # pragma: no cover
        raise ValueError(f"unknown profile: {profile}")
    return _HEADER + body + _VOLUMES


def write_stack_files(
    root: Path | str,
    *,
    profile: ComposeProfile | str,
    prometheus_yml: str,
    loki_config_src: Path | str | None = None,
) -> Path:
    """Write compose + configs under ``root``. Returns path to compose file."""
    root = Path(root)
    config = root / "config"
    config.mkdir(parents=True, exist_ok=True)

    compose_path = root / "docker-compose.yaml"
    compose_path.write_text(generate_compose_yaml(profile), encoding="utf-8")

    src = Path(loki_config_src) if loki_config_src else _ASSETS / "loki-config.yaml"
    shutil.copyfile(src, config / "loki-config.yaml")
    (config / "prometheus.yml").write_text(prometheus_yml, encoding="utf-8")
    return compose_path


def windows_wsl2_notes() -> str:
    """Operator-facing notes for the WSL2 NAT path (display in Setup Wizard)."""
    return (
        "Windows primary path: run Loki/Prometheus inside WSL2 Ubuntu "
        "(ComposeProfile.WSL2). Loki publishes 0.0.0.0:3100 inside WSL; "
        "Prometheus binds 127.0.0.1:9090 (localhostForwarding for UI). "
        "For Promtail on the LAN gateway, the Setup Wizard shows a guided "
        "netsh portproxy + firewall checklist for TCP 3100 only (K18) — "
        "commands are displayed for the user to run elevated; the app never "
        "auto-applies firewall/portproxy rules. FastAPI :9137 and Streamlit "
        ":8501 must NOT use portproxy; they rely on Windows localhostForwarding."
    )
