"""App-managed Loki + Prometheus as native OS processes (no Docker)."""

from __future__ import annotations

import os
import signal
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from .binary_fetch import BinaryFetchError, ensure_telemetry_binaries
from .lifecycle import BackendStatus
from .readiness import check_loki, check_prometheus, wait_ready
from .scrape import render_prometheus_scrape


def _render_loki_config(data_root: Path) -> str:
    """Single-node Loki config with all paths under ``data_root`` (never /loki)."""
    root = data_root.resolve()
    chunks = root / "chunks"
    rules = root / "rules"
    tsdb_index = root / "tsdb-index"
    tsdb_cache = root / "tsdb-cache"
    compactor = root / "compactor"
    wal = root / "wal"
    for d in (chunks, rules, tsdb_index, tsdb_cache, compactor, wal):
        d.mkdir(parents=True, exist_ok=True)
    # common.path_prefix is the base for WAL and other relative paths in Loki 3.x.
    prefix = root.as_posix()
    return f"""# Generated by telemetry.native — do not edit by hand.
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: {prefix}
  storage:
    filesystem:
      chunks_directory: {chunks.as_posix()}
      rules_directory: {rules.as_posix()}
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: {chunks.as_posix()}
  tsdb_shipper:
    active_index_directory: {tsdb_index.as_posix()}
    cache_location: {tsdb_cache.as_posix()}

ingester:
  wal:
    enabled: true
    dir: {wal.as_posix()}

compactor:
  working_directory: {compactor.as_posix()}
  compaction_interval: 10m

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  reject_old_samples: true
  reject_old_samples_max_age: 168h
"""


@dataclass
class NativeTelemetryStatus:
    ready: bool
    binaries_present: bool
    loki_running: bool
    prometheus_running: bool
    detail: str = ""
    progress: str = ""


class NativeTelemetryManager:
    """Fetch binaries once, then run Loki + Prometheus as child processes."""

    def __init__(self, root: Path | str):
        self.root = Path(root)
        self.bin_dir = self.root / "bin"
        self.config_dir = self.root / "config"
        self.loki_data = self.root / "loki-data"
        self.prom_data = self.root / "prometheus-data"
        self._loki: Optional[subprocess.Popen] = None
        self._prom: Optional[subprocess.Popen] = None
        self.last_progress: str = ""

    def _progress(self, msg: str, frac: float) -> None:
        self.last_progress = f"{msg} ({frac:.0%})"

    def ensure_binaries(self, *, force: bool = False) -> dict[str, Path]:
        return ensure_telemetry_binaries(
            self.bin_dir, progress=self._progress, force=force
        )

    def write_configs(self, *, gateway_ip: str = "127.0.0.1") -> None:
        self.config_dir.mkdir(parents=True, exist_ok=True)
        loki_cfg = self.config_dir / "loki-config.yaml"
        loki_cfg.write_text(_render_loki_config(self.loki_data), encoding="utf-8")
        prom_yml = render_prometheus_scrape(gateway_ip)
        (self.config_dir / "prometheus.yml").write_text(prom_yml, encoding="utf-8")
        self.prom_data.mkdir(parents=True, exist_ok=True)

    def _bin(self, name: str) -> Path:
        if os.name == "nt":
            cand = self.bin_dir / f"{name}.exe"
            if cand.is_file():
                return cand
        return self.bin_dir / name

    def _running(self, proc: Optional[subprocess.Popen]) -> bool:
        return proc is not None and proc.poll() is None

    def _http_ready(
        self,
        *,
        loki_url: str = "http://127.0.0.1:3100",
        prometheus_url: str = "http://127.0.0.1:9090",
        timeout: float = 2.0,
    ) -> tuple[bool, object, object]:
        loki = check_loki(loki_url, timeout=timeout)
        prom = check_prometheus(prometheus_url, timeout=timeout)
        return bool(loki.ok and prom.ok), loki, prom

    def status(
        self,
        *,
        loki_url: str = "http://127.0.0.1:3100",
        prometheus_url: str = "http://127.0.0.1:9090",
        probe: bool = True,
    ) -> BackendStatus:
        bins_ok = self._bin("loki").is_file() and self._bin("prometheus").is_file()
        child_loki = self._running(self._loki)
        child_prom = self._running(self._prom)
        status = BackendStatus(
            running=False,
            compose_ps=(
                f"native loki_child={'up' if child_loki else 'down'} "
                f"prometheus_child={'up' if child_prom else 'down'} "
                f"binaries={'yes' if bins_ok else 'no'}"
            ),
            detail="",
        )
        if not bins_ok:
            status.detail = "Monitoring binaries are not installed yet."
            return status
        if not probe:
            status.running = child_loki and child_prom
            status.detail = (
                "Loki and Prometheus child processes are running."
                if status.running
                else "Monitoring processes are not running."
            )
            return status

        ok, loki, prom = self._http_ready(
            loki_url=loki_url, prometheus_url=prometheus_url
        )
        status.loki = loki
        status.prometheus = prom
        status.running = ok
        if ok:
            status.detail = "Loki and Prometheus are running."
        else:
            parts = []
            if not loki.ok:
                parts.append(f"loki: {loki.detail}")
            if not prom.ok:
                parts.append(f"prometheus: {prom.detail}")
            status.detail = "; ".join(parts) or "Monitoring is not ready."
        return status

    def snapshot(self) -> NativeTelemetryStatus:
        st = self.status(probe=True)
        ok, loki, prom = self._http_ready()
        return NativeTelemetryStatus(
            ready=bool(st.running),
            binaries_present=self._bin("loki").is_file()
            and self._bin("prometheus").is_file(),
            loki_running=bool(getattr(loki, "ok", False)) or self._running(self._loki),
            prometheus_running=bool(getattr(prom, "ok", False))
            or self._running(self._prom),
            detail=st.detail or st.compose_ps,
            progress=self.last_progress,
        )

    def _popen_kwargs(self) -> dict:
        kwargs: dict = {
            "cwd": str(self.root),
            "stderr": subprocess.STDOUT,
        }
        if os.name == "nt":
            # Hide Loki/Prometheus console windows on Windows.
            kwargs["creationflags"] = getattr(subprocess, "CREATE_NO_WINDOW", 0)
        else:
            kwargs["start_new_session"] = True
        return kwargs

    def start(
        self,
        *,
        gateway_ip: str | None = None,
        wait: bool = True,
        wait_timeout_s: float = 90.0,
        ensure_bins: bool = True,
    ) -> BackendStatus:
        if ensure_bins:
            try:
                self.ensure_binaries()
            except BinaryFetchError as e:
                return BackendStatus(
                    running=False, compose_ps="native", detail=str(e)
                )

        # Already serving? Treat as success (orphans from a previous session, etc.).
        already_ok, loki_p, prom_p = self._http_ready()
        if already_ok:
            return BackendStatus(
                running=True,
                compose_ps="native (already running)",
                detail="Loki and Prometheus are running.",
                loki=loki_p,
                prometheus=prom_p,
            )

        self.write_configs(gateway_ip=gateway_ip or "127.0.0.1")
        loki_bin = self._bin("loki")
        prom_bin = self._bin("prometheus")
        if not loki_bin.is_file() or not prom_bin.is_file():
            return BackendStatus(
                running=False,
                compose_ps="native",
                detail="loki/prometheus binaries missing after ensure",
            )

        log_dir = self.root / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        popen_kwargs = self._popen_kwargs()

        if not self._running(self._loki) and not check_loki(
            "http://127.0.0.1:3100", timeout=1.0
        ).ok:
            loki_log = open(log_dir / "loki.log", "a", encoding="utf-8")  # noqa: SIM115
            self._loki = subprocess.Popen(
                [str(loki_bin), f"-config.file={self.config_dir / 'loki-config.yaml'}"],
                stdout=loki_log,
                **popen_kwargs,
            )
        if not self._running(self._prom) and not check_prometheus(
            "http://127.0.0.1:9090", timeout=1.0
        ).ok:
            prom_log = open(log_dir / "prometheus.log", "a", encoding="utf-8")  # noqa: SIM115
            self._prom = subprocess.Popen(
                [
                    str(prom_bin),
                    f"--config.file={self.config_dir / 'prometheus.yml'}",
                    f"--storage.tsdb.path={self.prom_data}",
                    "--web.listen-address=0.0.0.0:9090",
                    "--web.enable-lifecycle",
                ],
                stdout=prom_log,
                **popen_kwargs,
            )

        if wait:
            ready = wait_ready(
                loki_url="http://127.0.0.1:3100",
                prometheus_url="http://127.0.0.1:9090",
                timeout_s=wait_timeout_s,
            )
            st = BackendStatus(
                running=bool(ready) and all(r.ok for r in ready.values()),
                compose_ps="native",
                loki=ready.get("loki"),
                prometheus=ready.get("prometheus"),
            )
            if st.running:
                st.detail = "Loki and Prometheus are running."
            else:
                st.detail = self._failure_detail(ready)
            return st
        return self.status(probe=True)

    def _failure_detail(self, ready: dict) -> str:
        """Build an operator-facing error from probes + recent log tails."""
        parts: list[str] = []
        for name, result in (ready or {}).items():
            if result is not None and not result.ok:
                parts.append(f"{name}: {result.detail}")
        if self._loki is not None and self._loki.poll() is not None:
            parts.append(f"loki exited (code {self._loki.returncode})")
        if self._prom is not None and self._prom.poll() is not None:
            parts.append(f"prometheus exited (code {self._prom.returncode})")
        for log_name in ("loki.log", "prometheus.log"):
            path = self.root / "logs" / log_name
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            err_lines = [
                ln.strip()
                for ln in text.splitlines()
                if "level=error" in ln or "permission denied" in ln.lower()
            ]
            if err_lines:
                parts.append(f"{log_name}: {err_lines[-1][-240:]}")
        return "; ".join(parts) or "Monitoring failed to become ready."

    def stop(self, *, grace: float = 5.0) -> None:
        for proc in (self._prom, self._loki):
            if proc is None or proc.poll() is not None:
                continue
            try:
                if os.name != "nt":
                    os.killpg(proc.pid, signal.SIGTERM)
                else:
                    proc.terminate()
            except (ProcessLookupError, PermissionError, OSError):
                proc.terminate()
            deadline = time.time() + grace
            while time.time() < deadline and proc.poll() is None:
                time.sleep(0.1)
            if proc.poll() is None:
                try:
                    if os.name != "nt":
                        os.killpg(proc.pid, signal.SIGKILL)
                    else:
                        proc.kill()
                except (ProcessLookupError, PermissionError, OSError):
                    proc.kill()
        self._prom = None
        self._loki = None


def default_native_root() -> Path:
    """Prefer IOTGW_DATA_DIR/telemetry when set by the desktop shell."""
    base = os.environ.get("IOTGW_DATA_DIR", "").strip()
    if base:
        return Path(base).expanduser() / "telemetry"
    if os.name == "nt":
        appdata = os.environ.get("APPDATA") or str(Path.home())
        return Path(appdata) / "IoTGatewayMonitor" / "telemetry"
    return Path.home() / ".local" / "share" / "iot-gateway-monitor" / "telemetry"
